### ISSUE TITLE
Python 3.13 reading speed decline

### ISSUE THREAD

**Issue by rkrueck** [dimastbk/python-calamine#104]
Hi there, 
I've noticed a measurable decline in reading speed of python-calamine with Python 3.13.0 vs Python 3.12.7
For example the code snippet below:

```python
def parse_values(file_name: Path) -> list:
    print(f'parsing {file_name.name}')
    workbook = CalamineWorkbook.from_object(file_name)
    sheet = workbook.get_sheet_by_name(feature.sheet).to_python()

    return sheet
```

```python
values_list = []
for file in files:
    values_list.append(parse_values(file))
print(values_list)
```

I read 48 files with Python 3.12.7 in 0.3 s
Where as reading 48 files in Python 3.13.0 takes 1.3 s

This is exacerbated when I need to read files from a network drive. Is there an explanation?

**Comment by dimastbk** [comment]
Hi. I have made a few tests with `asv` and below my results. So, I don't see big difference in performance between 3.13 and other versions.

All benchmarks:

| Before [afddcd35] <v0.3.1>   | After [6e227c2b] <master>   |   Ratio | Benchmark (Parameter)                                                              |
|------------------------------|-----------------------------|---------|------------------------------------------------------------------------------------|
| 645±7ms                      | 636±3ms                     |    0.99 | benchmarks.TimeSuite.time_iter_rows [py3.10]       |
| 642±3ms                      | 637±3ms                     |    0.99 | benchmarks.TimeSuite.time_iter_rows [py3.11]       |
| 635±3ms                      | 631±3ms                     |    0.99 | benchmarks.TimeSuite.time_iter_rows [py3.12]       |
| 638±2ms                      | 627±7ms                     |    0.98 | benchmarks.TimeSuite.time_iter_rows [py3.13]       |
| 14.5±0.3ms                   | 14.9±0.5ms                  |    1.03 | benchmarks.TimeSuite.time_manyfiles_bytes [py3.10] |
| 14.6±0.2ms                   | 14.6±0.3ms                  |    1    | benchmarks.TimeSuite.time_manyfiles_bytes [py3.11] |
| 15.2±0.4ms                   | 14.5±0.2ms                  |    0.96 | benchmarks.TimeSuite.time_manyfiles_bytes [py3.12] |
| 15.3±0.3ms                   | 15.1±0.3ms                  |    0.98 | benchmarks.TimeSuite.time_manyfiles_bytes [py3.13] |
| 16.7±0.4ms                   | 17.2±0.6ms                  |    1.03 | benchmarks.TimeSuite.time_manyfiles_path [py3.10]  |
| 16.6±0.5ms                   | 16.7±0.4ms                  |    1.01 | benchmarks.TimeSuite.time_manyfiles_path [py3.11]  |
| 17.7±0.5ms                   | 16.2±0.4ms                  |    0.91 | benchmarks.TimeSuite.time_manyfiles_path [py3.12]  |
| 16.7±0.4ms                   | 17.8±0.4ms                  |    1.07 | benchmarks.TimeSuite.time_manyfiles_path [py3.13]  |
| 654±5ms                      | 653±4ms                     |    1    | benchmarks.TimeSuite.time_rows [py3.10]            |
| 662±4ms                      | 662±10ms                    |    1    | benchmarks.TimeSuite.time_rows [py3.11]            |
| 654±2ms                      | 654±2ms                     |    1    | benchmarks.TimeSuite.time_rows [py3.12]            |
| 656±2ms                      | 661±20ms                    |    1.01 | benchmarks.TimeSuite.time_rows [py3.13]            |

<details><summary>Code</summary>

```python
from python_calamine import load_workbook


class TimeSuite:
    def time_iter_rows(self) -> None:
        with load_workbook("65K_Records_Data.xlsx") as wb:
            sheet = wb.get_sheet_by_index(0)
            for row in sheet.iter_rows():
                assert row is not None

    def time_rows(self) -> None:
        with load_workbook("65K_Records_Data.xlsx") as wb:
            sheet = wb.get_sheet_by_index(0)
            for row in sheet.to_python():
                assert row is not None

    def time_manyfiles_path(self) -> None:
        for _ in range(100):
            with load_workbook("base.xlsx") as wb:
                sheet = wb.get_sheet_by_index(0)
                for row in sheet.to_python():
                    assert row is not None

    def time_manyfiles_bytes(self) -> None:
        for _ in range(100):
            with open(
                "base.xlsx",
                mode="rb",
            ) as f:
                wb = load_workbook(f)
                sheet = wb.get_sheet_by_index(0)
                for row in sheet.to_python():
                    assert row is not None
```

</details>
