### ISSUE TITLE
ModuleNotFoundError: No module named 'python_calamine.pandas'

### ISSUE THREAD

**Issue by rhkleijn** [dimastbk/python-calamine#2]
For my use case I would like to use calamine as engine in read_excel().

When I installed python-calamine 0.0.4 and  followed the instructions in the [README.md](https://github.com/dimastbk/python-calamine/blob/master/README.md#example) file:
```
from python_calamine.pandas import pandas_monkeypatch
```
it resulted in this error:
```
ModuleNotFoundError: No module named 'python_calamine.pandas'
```

It seems that the [pandas.py ](https://github.com/dimastbk/python-calamine/blob/master/python/pandas.py) file was not included in the wheels uploaded to pypi.

**Comment by dimastbk** [comment]
Thanks! I fixed this in [v0.0.5](https://github.com/dimastbk/python-calamine/releases/tag/v0.0.5).
