### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by benjamingr** [dimastbk/python-calamine#41]
Hey did you ever benchmark this against openpyxl or others?

**Comment by dimastbk** [comment]
Hi! You can see some benchmarks in https://github.com/dimastbk/python-calamine/pull/37.

**Comment by thinkh** [comment]
See also https://x.com/be_haki/status/1727966893951053908?t=XsQ-PnF8TP_8cBLMMzgKbw&s=09

**Comment by leogregianin** [comment]
Another benchmark by @Hakib comparing Pandas, Tablib, Openpyxl, LibreOffice, DuckDB and python-calamine here:  https://hakibenita.com/fast-excel-python
