### ISSUE TITLE
Pylance Type Hint Error

### ISSUE THREAD

**Issue by notatallshaw-gts** [dimastbk/python-calamine#46]
For the code:

```python
import python_calamine

def test_file_type():
    with open("foo.xlsx", "rb") as f:
        python_calamine.CalamineWorkbook.from_filelike(f)
```

Pylance gives the type hint error:

```
Argument of type "BufferedReader" cannot be assigned to parameter "filelike" of type "ReadBuffer" in function "from_filelike"
  "BufferedReader" is incompatible with protocol "ReadBuffer"
    "seek" is an incompatible type
      Type "(__offset: int, __whence: int = ..., /) -> int" cannot be assigned to type "() -> int"
        Position-only parameter mismatch; expected 1 but received 0
(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)

(variable) f: BufferedReader
```

If I'm understanding what you're trying to achieve and you don't want to use typeshed types, I would suggest copying how typeshed type hints methods, e.g. https://github.com/python/typeshed/blob/main/stdlib/io.pyi#L70

So your `ReadBuffer` should be:

```python
class ReadBuffer(Protocol):
    def seek(self, __offset: int, __whence: int = ...) -> int: ...
    def read(self, __size: int = -1) -> bytes | None: ...
```

I'd be happy to make a PR in the new year if you'd like.

**Comment by dimastbk** [comment]
> If I'm understanding what you're trying to achieve and you don't want to use typeshed types

We need only 2 methods for work, so in my opinion, using protocol makes sense.

I synced signatures with typeshed. Thanks for the report!
