### ISSUE TITLE
Colour in excel file and iterrows ? 

### ISSUE THREAD

**Issue by jc77100** [dimastbk/python-calamine#54]
Hi , 

I would like to know if it would be possible within your library to extract the colour of the excel files (e.g : extract all cells that have highlighted background in colour : '00FFAFAF' ? 

Also, i can see another thread about the possibility to use iterrows(), is it something possible now ? 

Currently using openpyxl but it's taking ~ 20 sec per file (have a folder with 200+ files) to read all those infos ( i cant use the data mode as it do not support the colour)...

Thanks in advance for your time, 
Please note that i'm not a software dev.

**Comment by dimastbk** [comment]
Hi!

> I would like to know if it would be possible within your library to extract the colour of the excel files (e.g : extract all cells that have highlighted background in colour : '00FFAFAF' ?

No, calamine (and python-calamine) doesn't support this.

> Also, i can see another thread about the possibility to use iterrows(), is it something possible now ?

No, I work on this.
