### ISSUE TITLE
No way to close a CalamineWorkbook?

### ISSUE THREAD

**Issue by RedAero** [dimastbk/python-calamine#91]
There is no .close() method and as far as I can tell a with block has no effect either. Can these features please be implemented so the file being read doesn't remain locked until the executing program closes?

**Comment by dimastbk** [comment]
Hi. Could you give a reproducible example?

**Comment by RedAero** [comment]
A reproducible example of a missing feature?

Sure. Create a CalamineWorkbook then try to close it.

**Comment by dimastbk** [comment]
Released in 0.3.0. But `close` only prevents the fd from leaking and frees resources, and doesn't unlock the file, because of the file has never been locked before (at least on linux).
